# Generated by Django 3.2.7 on 2021-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='production',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
    ]
