# Generated by Django 3.2.7 on 2021-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_auto_20211005_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='raiting',
            field=models.IntegerField(default=5),
        ),
    ]
